eyes = input("\nPlease input a symbol for the eyes!\n")

print("\n      #########")
print(f"      # {eyes}   {eyes} #")
print("    ###   -   ###")
print("      #  ---  #")
print("      #########")
print("         ###")
print("  #################")
print("  ### ######### ###")
print("  ### ######### ###")
print("  ### ######### ###")
print("   #  #########  # ")
print("  ### ######### ###")
print("  ### ######### ###")
print("  ###  #######  ###")
print("      #########")
print("      ###   ###")
print("      ###   ###")
print("      ###   ###")
print("      ###   ###")
print("      ###   ###")
print("       #     # ")
print("      ###   ###")
print("      ###   ###")
print("      ###   ###")
print("      ###   ###")
print("      ###   ###")
